name: Build NPM package from sources

on:
  workflow_call:
    inputs:
      ignore-cache:
        required: false
        type: boolean
        description: build without node_modules cache
      node-version:
        required: false
        type: string
        default: latest
        description: NodeJS version for build process

concurrency:
  group: ${{ github.repository }}/${{ github.ref_name }}/${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Build NPM package'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache dependencies
        id: cache-deps
        if: ${{ ! inputs.ignore-cache }}
        uses: actions/cache@v5
        with:
          path: node_modules
          key: OS:ubuntu-latest:Node:latest:package.json:${{hashFiles('package.json')}}

      - name: Install dependencies
        # if: ${{ inputs.ignore-cache || ! steps.cache-deps.outputs.cache-hit }}
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload package 'dist'
        uses: actions/upload-artifact@v6
        with:
          name: dist
          path: dist/

      - name: Pack
        run: npm pack

      - name: Upload package tarball
        uses: actions/upload-artifact@v6
        with:
          name: Package tarball
          path: ./*.tgz
          if-no-files-found: error
          overwrite: true
