name: Check changes in dependencies

on:
  workflow_call:

concurrency:
  group: ${{ github.repository }}/${{ github.ref }}/${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check for new and updated dependencies
        uses: rknj/dependencies-updates-action@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          show_dev_dependencies: 'false'
