---
name: Deployment to GitHub releases

on:
  workflow_call:
    inputs:
      deployment-environment:
        description: GitHub deployment environment
        required: false
        type: string
        default: GitHub-Releases
      os:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: Operation system for build process
      node-version:
        required: false
        type: string
        default: latest
        description: NodeJS version for build process
    outputs:
      is-new-release:
        description: predicate - is new release published?
        value: ${{jobs.deployment.outputs.is-new-release}}
      version:
        description: release version
        value: ${{jobs.deployment.outputs.version}}

concurrency:
  group: ${{ github.repository }}/${{ github.ref_name }}/${{ github.workflow }}/${{ github.job }}
  cancel-in-progress: true

jobs:
  deployment:
    environment: ${{ inputs.deployment-environment }}
    if: github.event_name == 'workflow_run' || github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      actions: read
      deployments: write
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    outputs:
      is-new-release: ${{steps.release-to-GitHub.outputs.new-release-published}}
      version: ${{steps.release-to-GitHub.outputs.release-version}}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          package-manager-cache: true
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install

      - name: Download package 'dist'
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: dist/

      - name: Update API documentation
        run: npm run update-readme-API

      - name: Update readme.md
        run: npm run update-readme

      - uses: codfish/semantic-release-action@v5
        id: release-to-GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload package files
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: |
            package.json
            dist/
            readme.md
          if-no-files-found: error
          retention-days: 1
