name: Lint source code, documentation

on:
  workflow_call:
    inputs:
      ignore-cache:
        required: false
        type: boolean
        description: build without node_modules cache
      os:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: Operation system for build process
      node-version:
        required: false
        type: string
        default: latest
        description: NodeJS version for build process

concurrency:
  group: ${{ github.repository }}/${{ github.ref_name }}/${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    name: 'Lint source code, documentation'
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Cache dependencies
        id: cache-deps
        if: ${{ ! inputs.ignore-cache }}
        uses: actions/cache@v5
        with:
          path: node_modules
          key: OS:${{ inputs.os }}:Node:${{ inputs.node-version }}:package.json:${{hashFiles('package.json')}}

      - name: Install dependencies
        # if: ${{ inputs.ignore-cache || ! steps.cache-deps.outputs.cache-hit }}
        run: npm install

      - name: Lint
        run: npm run lint
