---
name: Lint source code, documentation

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: Operation system for build process
      log-level:
        required: false
        type: string
        default: INFO
        description: How much output the script will generate to the console. One of ERROR, WARN, NOTICE, INFO, or DEBUG

jobs:
  lint:
    name: 'Lint source code, documentation'
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup NodeJS ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: npm
          package-manager-cache: true
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: pnpm run --if-present --recursive build

      - name: Lint
        # run: npm run lint
        uses: super-linter/super-linter/slim@v8.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          # VALIDATE_GITHUB_ACTIONS_ZIZMOR: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_YAML: true
          TYPESCRIPT_ES_CONFIG_FILE: eslint.config.ts
          LINTER_RULES_PATH: .
          LOG_LEVEL: ${{ inputs.log-level }}
