name: Test

on:
  workflow_call:

concurrency:
  group: ${{ github.repository }}/${{ github.ref_name }}/${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: ['20.x', '21.x', '22.x', '23.x', '24.x', 'latest']
        include:
          - os: 'ubuntu-latest'
            node-version: 'latest'
            main-test-environment: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: node_modules
          key: OS:${{ matrix.os }}:Node:${{ matrix.node-version }}:package.json:${{hashFiles('package.json')}}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

      - name: Download package 'dist'
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist/

      # - name: Check module exports
      #   if: matrix.main-test-environment
      #   run: npm run check-exports

      - name: Test
        run: npm run test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: Test Results (OS ${{ matrix.os }} - Node.js ${{ matrix.node-version }})
          path: test/results/junit-report.xml

      - name: Upload Test Coverage
        if: matrix.main-test-environment
        uses: actions/upload-artifact@v6
        with:
          name: Coverage
          path: coverage/coverage-summary.json

      - name: Report Coverage
        if: matrix.main-test-environment
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all

