name: Test

on:
  workflow_call:
    inputs:
      badges-gist-id:
        required: false
        type: string
        description: gist id for badges publishing
        default: ${{ vars.BADGES_GIST_ID }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: ['22.x', '23.x', '24.x', 'latest']
        include:
          - os: 'ubuntu-latest'
            node-version: 'latest'
            main-test-environment: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          package-manager-cache: true
          cache-dependency-path: package.json, packages/*/package.json

      - uses: pnpm/action-setup@v4
        name: Install pnpm and packages
        with:
          run_install: true

      - name: Download package 'dist'
        uses: actions/download-artifact@v8
        with:
          name: dist
          path: packages/

      - name: Test
        run: pnpm run --if-present --recursive test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results--${{ matrix.os }}--${{ matrix.node-version }}
          path: packages/*/test/results/junit-report.xml

      - name: Upload Test Coverage
        if: matrix.main-test-environment
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: packages/*/coverage/

  publish-test-results:
    name: Test results publishing
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    env:
      publish-to-coveralls: ${{ secrets.COVERALLS_REPO_TOKEN != '' }}

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: test-results--*
          path: packages/
          merge-multiple: false

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: coverage
          path: packages/

      - name: Publish tests results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        with:
          files: packages/*/test/results/**/*.xml
