name: Test

on:
  workflow_call:
    inputs:
      badges-gist-id:
        required: false
        type: string
        description: gist id for badges publishing
        default: ${{ vars.BADGES_GIST_ID }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: ['22.x', '23.x', '24.x', 'latest']
        include:
          - os: 'ubuntu-latest'
            node-version: 'latest'
            main-test-environment: true

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup NodeJS ${{ matrix.node-version }}
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: node_modules
          key: OS:${{ matrix.os }}:Node:${{ matrix.node-version }}:package.json:${{hashFiles('package.json')}}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm install

      - name: Download package 'dist'
        uses: actions/download-artifact@v6
        with:
          name: dist
          path: dist/

      - name: Test
        run: npm run test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results--${{ matrix.os }}--${{ matrix.node-version }}
          path: test/results/junit-report.xml

      - name: Upload Test Coverage
        if: matrix.main-test-environment
        uses: actions/upload-artifact@v6
        with:
          name: coverage
          path: coverage/

      - name: Report Coverage
        if: matrix.main-test-environment && hashFiles('vitest.config.ts') != ''
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all

  publish-test-results:
    name: Test results publishing
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    if: always()
    env:
      publish-to-coveralls: ${{ secrets.COVERALLS_REPO_TOKEN != '' }}

    steps:

      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: test-results--*
          path: test/results
          merge-multiple: false

      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          name: coverage
          path: coverage/

      - name: Publish tests results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        with:
          files: 'test/results/**/*.xml'

      - uses: gaelgirodon/ci-badges-action@v1
        with:
          gist-id: ${{ inputs.badges-gist-id }}
          token: ${{ secrets.GIST_TOKEN }}

      - uses: coverallsapp/github-action@v2
        if: env.publish-to-coveralls == 'true'
